"""rename address

Revision ID: 637c728ef3cd
Revises: 11968d06b3fb
Create Date: 2023-11-14 13:19:14.876164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637c728ef3cd'
down_revision = '11968d06b3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'address', new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')

    # ### end Alembic commands ###
